services:
  # Un service web pour l'API
  - type: web
    name: abtest-calculator-api
    env: python
    buildCommand: pip install -r app/requirements.txt
    startCommand: cd app && uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11 